version: "3"

tasks:
  fix-ssh:
    desc: Fix SSH permissions for mounted keys
    cmds:
      - |
        echo "Fixing SSH permissions..."
        chmod 700 /root/.ssh
        chmod 600 /root/.ssh/config /root/.ssh/id_* 2>/dev/null || true
        chmod 644 /root/.ssh/*.pub 2>/dev/null || true
        chown -R root:root /root/.ssh 2>/dev/null || true
        echo "✓ SSH permissions fixed"

  git-signing:
    desc: Configure SSH signing key for Git commits
    cmds:
      - |
        SIGNING_KEY="/root/.ssh/id_ed25519_signing.pub"

        if [ ! -f "$SIGNING_KEY" ]; then
          echo "Error: SSH signing key not found at $SIGNING_KEY"
          exit 1
        fi

        echo "Setting up Git commit signing with SSH key..."
        git config --global gpg.format ssh
        git config --global user.signingkey "$SIGNING_KEY"
        git config --global commit.gpgsign true
        git config --global tag.gpgsign true

        echo "✓ Git signing configured:"
        echo "  Key: $SIGNING_KEY"
        echo "  Commits: signed"
        echo "  Tags: signed"

  setup-all:
    desc: Run all setup tasks
    cmds:
      - task: fix-ssh
      - task: git-signing
