version: "3"

tasks:
  git-signing:
    desc: Configure SSH signing key for Git commits
    cmds:
      - |
        SIGNING_KEY="/root/.ssh/id_ed25519_signing.pub"

        if [ ! -f "$SIGNING_KEY" ]; then
          echo "Error: SSH signing key not found at $SIGNING_KEY"
          exit 1
        fi

        echo "Setting up Git commit signing with SSH key..."
        git config --global gpg.format ssh
        git config --global user.signingkey "$SIGNING_KEY"
        git config --global commit.gpgsign true
        git config --global tag.gpgsign true

        echo "✓ Git signing configured:"
        echo "  Key: $SIGNING_KEY"
        echo "  Commits: signed"
        echo "  Tags: signed"
