"""Validation table: angular error of every method on DADS clips with random directions.

Each clip gets one random direction on the upper hemisphere and one random 100 ms segment,
the same for all methods and both SNRs (paired comparison). Writes ``validation.tex`` with
``\\validN``, ``\\validSnrHigh``, ``\\validSnrLow`` and the table body ``\\validrows`` that
``main.tex`` pastes into a ``tabular``. Deterministic: every task draws from its own seeded
generator, so the result does not depend on the worker count or completion order.
"""

from __future__ import annotations

import argparse
import os
import warnings
from concurrent.futures import ProcessPoolExecutor
from dataclasses import replace
from pathlib import Path

import numpy as np

from beamforming import dads, doa, pra_check
from beamforming import geometry as g
from beamforming import signals as sg

SEED = 2026
DEFAULT_SNRS = (30.0, 10.0)
DIAMETER, HEIGHT = 0.20, 0.07

# (label, kind, name); kind: own = coarse + fine search, coarse = grid maximum only, pra = pra
GROUPS: list[list[tuple[str, str, str]]] = [
    [
        ("DAS", "own", "das"),
        ("MVDR", "own", "mvdr"),
        ("SRP-PHAT", "own", "srp_phat"),
        ("GCC-PHAT + LS", "own", "gcc_phat_ls"),
        ("MUSIC", "own", "music"),
    ],
    [
        ("SRP-PHAT (hrubý grid)", "coarse", "srp_phat"),
        ("MUSIC (hrubý grid)", "coarse", "music"),
        ("SRP (pra)", "pra", "SRP"),
        ("NormMUSIC (pra)", "pra", "NormMUSIC"),
        ("CSSM (pra)", "pra", "CSSM"),
        ("WAVES (pra)", "pra", "WAVES"),
    ],
]
METHODS = [m for group in GROUPS for m in group]


def run_method(kind: str, name: str, x: np.ndarray, X: np.ndarray, mic: np.ndarray) -> np.ndarray:
    cfg = doa.DEFAULT
    if kind == "own":
        a, e = doa.localize(name, x, mic, cfg)
    elif kind == "coarse":
        a, e = doa.localize(name, x, mic, replace(cfg, fine_span=0.0))
    else:
        a, e = pra_check.locate(name, X, mic, cfg)
    return g.unit_vector(a, e)


def trial(task: tuple[int, Path, np.ndarray, tuple[float, ...]]) -> np.ndarray:
    """Angular errors (n_snr, n_methods) in degrees for one clip."""
    idx, path, u, snrs = task
    warnings.filterwarnings("ignore")
    mic = g.make_array("2x8_rot", DIAMETER, HEIGHT)
    clip = dads.load_clip(path)
    offset = dads.random_offset(len(clip), np.random.default_rng([SEED, idx, 0]))
    clean = sg.observe(clip, mic, u, offset)
    out = np.empty((len(snrs), len(METHODS)))
    for s, snr in enumerate(snrs):
        x = sg.add_noise(clean, snr, np.random.default_rng([SEED, idx, 1 + s]))
        X = sg.stft(x)
        for m, (_, kind, name) in enumerate(METHODS):
            out[s, m] = g.angular_error_deg(run_method(kind, name, x, X, mic), u)
    return out


def czech(x: float) -> str:
    return f"{x:.1f}".replace(".", "{,}")


def write_tex(path: Path, errors: np.ndarray, snrs: tuple[float, ...]) -> None:
    """``errors`` has shape (n_clips, n_snr, n_methods)."""
    median = np.median(errors, axis=0)
    rmse = np.sqrt(np.mean(errors**2, axis=0))
    rows: list[str] = []
    for gi, group in enumerate(GROUPS):
        if gi:
            rows.append("\\midrule")
        for label, _, _ in group:
            m = METHODS.index(next(t for t in group if t[0] == label))
            cells = [czech(v) for s in range(len(snrs)) for v in (median[s, m], rmse[s, m])]
            rows.append(f"{label} & " + " & ".join(cells) + " \\\\")
    body = "\n".join(rows)
    text = (
        "% generated by python/scripts/validate.py\n"
        f"\\newcommand{{\\validN}}{{{errors.shape[0]}}}\n"
        f"\\newcommand{{\\validSnrHigh}}{{{snrs[0]:.0f}}}\n"
        f"\\newcommand{{\\validSnrLow}}{{{snrs[1]:.0f}}}\n"
        f"\\newcommand{{\\validrows}}{{%\n{body}}}\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("report/generated/validation.tex"))
    parser.add_argument("--data", type=Path, default=dads.DEFAULT_OUT)
    parser.add_argument("--limit", type=int, default=0, help="use only the first N clips (debug)")
    parser.add_argument("--snrs", type=float, nargs=2, default=DEFAULT_SNRS, help="high low (dB)")
    parser.add_argument("--workers", type=int, default=os.cpu_count() or 1)
    args = parser.parse_args()

    snrs = (float(args.snrs[0]), float(args.snrs[1]))
    clips = dads.list_clips(args.data)
    if args.limit:
        clips = clips[: args.limit]
    dirs = g.random_directions(len(clips), np.random.default_rng(SEED))
    tasks = [(c.index, c.path, dirs[i], snrs) for i, c in enumerate(clips)]
    with ProcessPoolExecutor(max_workers=args.workers) as pool:
        errors = np.stack(list(pool.map(trial, tasks, chunksize=1)))
    write_tex(args.out, errors, snrs)

    print(f"{len(clips)} clips; median / RMSE of the angular error in degrees")
    for s, snr in enumerate(snrs):
        print(f"SNR {snr:.0f} dB")
        for m, (label, kind, _) in enumerate(METHODS):
            e = errors[:, s, m]
            rmse = np.sqrt(np.mean(e**2))
            print(f"  {label:18s} {kind:6s} median {np.median(e):5.2f}  rmse {rmse:5.2f}")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
