version: "3"

includes:
  fw:
    taskfile: ./fw/Taskfile.yml
    dir: ./fw
    optional: true
  api:
    taskfile: ./apps/api-backend/Taskfile.yml
    dir: ./apps/api-backend
    optional: true
  scripts:
    taskfile: ./scripts/Taskfile.yml
    dir: ./scripts
    optional: true

tasks:
  changeset:
    cmds:
      - pnpm changeset
    desc: Create a new changeset

  changeset:version:
    cmds:
      - pnpm changeset version
    desc: Apply versions from pending changesets

  docs:
    desc: Build documentation (Doxygen + Sphinx)
    deps:
      - docs:root
      - docs:firmware
      - docs:monorepo
      - docs:scripts

  docs:root:
    desc: Build root landing page only
    cmds:
      - sphinx-build -b html docs docs/_build/html

  docs:firmware:
    desc: Build firmware documentation only
    cmds:
      - PROJECT=firmware sphinx-build -b html docs docs/_build/firmware/html

  docs:monorepo:
    desc: Build monorepo documentation only
    cmds:
      - PROJECT=monorepo sphinx-build -b html docs docs/_build/monorepo/html

  docs:scripts:
    desc: Build scripts documentation only (includes Doxygen)
    cmds:
      - doxygen Doxyfile
      - PROJECT=scripts sphinx-build -b html docs docs/_build/scripts/html
