version: "3"

includes:
  fw:
    taskfile: ./fw/Taskfile.yml
    dir: ./fw
    optional: true
  api:
    taskfile: ./apps/api-backend/Taskfile.yml
    dir: ./apps/api-backend
    optional: true
  scripts:
    taskfile: ./scripts/Taskfile.yml
    dir: ./scripts
    optional: true

tasks:
  changeset:
    cmds:
      - pnpm changeset
    desc: Create a new changeset

  changeset:version:
    cmds:
      - pnpm changeset version
    desc: Apply versions from pending changesets

  docs:
    desc: Build documentation (Doxygen + Sphinx)
    cmds:
      - task docs:assemble

  docs:root:
    desc: Build root landing page only
    internal: true
    cmds:
      - sphinx-build -b html docs docs/_build/html

  docs:firmware:
    desc: Build firmware documentation only
    internal: true
    cmds:
      - PROJECT=firmware sphinx-build -b html docs docs/_build/firmware/html

  docs:monorepo:
    desc: Build monorepo documentation only
    internal: true
    cmds:
      - PROJECT=monorepo sphinx-build -b html docs docs/_build/monorepo/html

  docs:scripts:
    desc: Build scripts documentation only (includes Doxygen)
    internal: true
    cmds:
      - doxygen Doxyfile
      - PROJECT=scripts sphinx-build -b html docs docs/_build/scripts/html

  docs:assemble:
    desc: Copy per-project builds under the root HTML output for local previews
    internal: true
    deps:
      - docs:root
      - docs:firmware
      - docs:monorepo
      - docs:scripts
    cmds:
      - |
        set -euo pipefail
        mkdir -p docs/_build/html
        rm -rf docs/_build/html/firmware docs/_build/html/monorepo docs/_build/html/scripts
        mkdir -p docs/_build/html/firmware docs/_build/html/monorepo docs/_build/html/scripts
        rsync -a docs/_build/firmware/html/ docs/_build/html/firmware/
        rsync -a docs/_build/monorepo/html/ docs/_build/html/monorepo/
        rsync -a docs/_build/scripts/html/ docs/_build/html/scripts/
