version: "3"

includes:
  device-web:
    taskfile: ../../apps/device-web/Taskfile.yml
    dir: ../../apps/device-web
    optional: true

tasks:
  build:
    desc: Build ESP32 code
    aliases: [b]
    deps:
      - device-web:build
    cmds:
      - idf.py build

  flash:
    desc: Flash ESP32 code
    aliases: [f]
    cmds:
      - idf.py flash

  monitor:
    desc: Monitor ESP32
    aliases: [m]
    cmds:
      - idf.py monitor -p /dev/ttyUSB1
