#ifndef BOOMDETECT_ENVELOPE_COEFS_H
#define BOOMDETECT_ENVELOPE_COEFS_H

/*
 * The envelope chain of dsp/mfcc.py, as the C runs it
 *
 * GENERATED by fw/common/boomdetect/training (bdtrain export); do not edit.
 * generated: 2026-10-09T20:03:45 by bdtrain fixtures
 * band-pass: Butterworth order 2, 1000-4000 Hz at 16000 Hz (scipy.signal.butter, sos), sections 0..1
 * low-pass: Butterworth order 2, 400 Hz, section 2
 * a row is b0, b1, b2, a1, a2 with a0 == 1; direct form II transposed, like sosfilt
 */

#include <stdint.h>

#define BOOMDETECT_ENV_SOS_SECTIONS 3u
#define BOOMDETECT_ENV_BANDPASS_SECTIONS 2u
#define BOOMDETECT_ENV_COEFS_DECIM 16u
#define BOOMDETECT_ENV_COEFS_PER_HOP 32u
#define BOOMDETECT_ENV_COEFS_RING 1984u

static const float boomdetect_env_sos[3][5] = {
    { 0.186694339f, 0.373388678f, 0.186694339f, -0.162921786f, 0.327197969f, },
    { 1.0f, -2.0f, 1.0f, -1.48276079f, 0.640943348f, },
    { 0.00554271741f, 0.0110854348f, 0.00554271741f, -1.77863181f, 0.800802648f, },
};

#endif /* BOOMDETECT_ENVELOPE_COEFS_H */
