"""The C translation units the exported models need, and the CNN weight header.

export.py writes the weight tables. A table is not a model until a translation
unit under models/ wraps it in a classifier_t and the registry lists it; those
files are short and identical in shape for every model of a family, so they are
generated too - a hand-written one per model would be forty lines of copy and
paste per experiment.

What is NOT generated: the two lines in models/models.h and
src/classifier_registry.c that register a model. Adding a model to the board is
meant to be a visible edit in a file called "registry" (see that file's
header), and the parity test fails loudly for any exported model the registry
does not list, so forgetting is not silent.
"""

from __future__ import annotations

import numpy as np

from boomdetect_train.export import _c_array, _c_float, _header
from boomdetect_train.features import LAYOUT_LOGMEL, LAYOUT_STATS, LAYOUT_STATS_SPECTRAL
from boomdetect_train.models.cnn import L_CONV, L_DENSE, L_DWCONV, L_GAP, L_POOL, CnnModel

LAYOUT_MACRO = {
    LAYOUT_STATS: ("BOOMDETECT_LAYOUT_MEAN_STD_DMEAN_CMAX", "BOOMDETECT_FEATURE_COUNT"),
    LAYOUT_STATS_SPECTRAL: (
        "BOOMDETECT_LAYOUT_STATS_SPECTRAL",
        "BOOMDETECT_FEATURE_COUNT_STATS_SPECTRAL",
    ),
    LAYOUT_LOGMEL: ("BOOMDETECT_LAYOUT_LOGMEL", "BOOMDETECT_FEATURE_COUNT_LOGMEL"),
}


def _tu_header(name: str, what: str, provenance: list[str]) -> str:
    lines = [
        "/**",
        f" * @file model_{name}.c",
        f" * @brief {what}",
        " *",
        " * GENERATED by fw/common/boomdetect/training (bdtrain export); do not edit.",
        " * Registered by hand in models/models.h and src/classifier_registry.c.",
    ]
    lines += [f" * {p}" for p in provenance]
    lines.append(" */")
    return "\n".join(lines)


def mlp_tu(name: str, layout: int, offset: int, thr_milli: int, provenance: list[str]) -> str:
    layout_macro, width_macro = LAYOUT_MACRO[layout]
    head = _tu_header(name, f"MLP {name}: scaler, one hidden ReLU layer, logit output.", provenance)
    return f"""{head}
#include "classifier.h"
#include "dsp_config.h"
#include "models.h"

#include "arm_math.h"
#include "mlp_model_data_{name}.h"

#define OFFSET {offset}u

_Static_assert(OFFSET + MLP_NUM_INPUTS == {width_macro},
               "{name}'s slice does not cover the features its layout produces");

static float decide(void *ctx, const float *features, uint16_t n)
{{
    (void)n;
    (void)ctx;
    float32_t x[MLP_NUM_INPUTS];
    float32_t h[MLP_HIDDEN];
    for (uint32_t i = 0u; i < MLP_NUM_INPUTS; i++)
    {{
        x[i] = (features[i] - mlp_scaler_mean[i]) * mlp_scaler_inv_std[i];
    }}
    for (uint32_t j = 0u; j < MLP_HIDDEN; j++)
    {{
        float32_t acc = 0.0f;
        arm_dot_prod_f32(x, mlp_w1[j], MLP_NUM_INPUTS, &acc);
        acc += mlp_b1[j];
        h[j] = (acc > 0.0f) ? acc : 0.0f;
    }}
    float32_t out = 0.0f;
    arm_dot_prod_f32(h, mlp_w2, MLP_HIDDEN, &out);
    return out + MLP_B2;
}}

const classifier_t classifier_{name} = {{
    .name              = "{name}",
    .layout_id         = {layout_macro},
    .n_features        = MLP_NUM_INPUTS,
    .feature_offset    = OFFSET,
    .default_thr_milli = {thr_milli},
    .decide            = decide,
    .ctx               = NULL,
}};
"""


def linear_tu(name: str, layout: int, offset: int, thr_milli: int, provenance: list[str]) -> str:
    layout_macro, width_macro = LAYOUT_MACRO[layout]
    return f"""{_tu_header(name, f"Linear SVM {name}: scaler and a dot product.", provenance)}
#include "classifier.h"
#include "dsp_config.h"
#include "models.h"

#include "arm_math.h"
#include "svm_model_data_{name}.h"

#define OFFSET {offset}u

_Static_assert(OFFSET + SVM_NUM_FEATURES <= {width_macro},
               "{name}'s slice runs past the features its layout produces");

static float decide(void *ctx, const float *features, uint16_t n)
{{
    (void)n;
    (void)ctx;
    float32_t scaled[SVM_NUM_FEATURES];
    float32_t dot = 0.0f;
    for (uint32_t i = 0u; i < SVM_NUM_FEATURES; i++)
    {{
        scaled[i] = (features[i] - svm_scaler_mean[i]) * svm_scaler_inv_std[i];
    }}
    arm_dot_prod_f32(scaled, svm_weights, SVM_NUM_FEATURES, &dot);
    return dot + SVM_BIAS;
}}

const classifier_t classifier_{name} = {{
    .name              = "{name}",
    .layout_id         = {layout_macro},
    .n_features        = SVM_NUM_FEATURES,
    .feature_offset    = OFFSET,
    .default_thr_milli = {thr_milli},
    .decide            = decide,
    .ctx               = NULL,
}};
"""


def gbt_tu(name: str, layout: int, offset: int, thr_milli: int, provenance: list[str]) -> str:
    layout_macro, width_macro = LAYOUT_MACRO[layout]
    head = _tu_header(
        name, f"Gradient-boosted trees {name}: a forest walk, log-odds output.", provenance
    )
    return f"""{head}
#include "classifier.h"
#include "dsp_config.h"
#include "models.h"

#include "gbt_model_data_{name}.h"

#define OFFSET {offset}u

_Static_assert(OFFSET + GBT_NUM_FEATURES <= {width_macro},
               "{name}'s slice runs past the features its layout produces");

/* No scaler: a tree compares each feature against thresholds learned on the raw
   value, so standardising would only move the thresholds. Each tree is walked
   from its root until a leaf (feature GBT_LEAF); the leaf values sum onto the
   baseline log-odds. x <= threshold goes left, scikit-learn's convention. */
static float decide(void *ctx, const float *features, uint16_t n)
{{
    (void)n;
    (void)ctx;
    float acc = GBT_BASELINE;
    for (uint32_t t = 0u; t < GBT_NUM_TREES; t++)
    {{
        uint32_t node = gbt_tree_root[t];
        /* Bounded by the node count: a corrupt table cannot loop forever. */
        for (uint32_t guard = 0u; guard < GBT_NUM_NODES; guard++)
        {{
            const uint8_t f = gbt_node_feature[node];
            if (f == GBT_LEAF)
            {{
                break;
            }}
            node = (features[f] <= gbt_node_threshold[node]) ? gbt_node_left[node]
                                                            : gbt_node_right[node];
        }}
        acc += gbt_node_value[node];
    }}
    return acc;
}}

const classifier_t classifier_{name} = {{
    .name              = "{name}",
    .layout_id         = {layout_macro},
    .n_features        = GBT_NUM_FEATURES,
    .feature_offset    = OFFSET,
    .default_thr_milli = {thr_milli},
    .decide            = decide,
    .ctx               = NULL,
}};
"""


def cnn_header(model: CnnModel, name: str, provenance: list[str]) -> str:
    """nn_model_data_<name>.h: weight arrays and the nn_layer_t table."""
    net = model.net
    guard = f"NN_MODEL_DATA_{name.upper()}_H"
    lines = _header(
        guard,
        f"CNN {name} ({net.name}): {net.macs} MACs, {net.params} parameters, "
        f"{len(net.layers)} layers",
        provenance,
    )
    lines += ['#include "nn_infer.h"', ""]
    for i, layer in enumerate(net.layers):
        if layer.weight is None:
            continue
        w = layer.weight.reshape(-1)
        lines += [
            _c_array(f"nn_w{i}", "float", w, (w.shape[0],), _c_float),
            "",
            _c_array(f"nn_b{i}", "float", layer.bias, (layer.bias.shape[0],), _c_float),
            "",
        ]
    kinds = {
        L_CONV: "NN_CONV",
        L_DWCONV: "NN_DWCONV",
        L_POOL: "NN_POOL",
        L_GAP: "NN_GAP",
        L_DENSE: "NN_DENSE",
    }
    lines.append(f"static const nn_layer_t nn_layers_{name}[{len(net.layers)}] = {{")
    for i, layer in enumerate(net.layers):
        ic, ih, iw = layer.in_shape
        oc, oh, ow = layer.out_shape
        kh, kw = layer.kernel
        ph, pw = layer.pad
        w_ref = f"nn_w{i}" if layer.weight is not None else "NULL"
        b_ref = f"nn_b{i}" if layer.bias is not None else "NULL"
        lines.append(
            f"    {{ {kinds[layer.kind]}, {1 if layer.relu else 0}u, {ic}u, {ih}u, {iw}u, "
            f"{oc}u, {oh}u, {ow}u, {kh}u, {kw}u, {ph}u, {pw}u, {w_ref}, {b_ref} }},"
        )
    lines.append("};")
    in_layout = "NN_IN_FRAME_MAJOR" if net.input_layout == 0 else "NN_IN_MEL_CHANNELS"
    lines += [
        "",
        f"#define NN_MAX_ACT_{name.upper()} {net.max_activation}u",
        f"#define NN_MACS_{name.upper()} {net.macs}u",
        "",
        f"static const nn_net_t nn_net_{name} = {{",
        f"    {in_layout}, {len(net.layers)}u, nn_layers_{name}, {net.max_activation}u, "
        f"{model.n_features}u,",
        "};",
        "",
        f"#endif /* {guard} */",
        "",
    ]
    return "\n".join(lines)


def cnn_tu(name: str, thr_milli: int, provenance: list[str], mac_budget: int = 1_500_000) -> str:
    layout_macro, width_macro = LAYOUT_MACRO[LAYOUT_LOGMEL]
    up = name.upper()
    head = _tu_header(name, f"CNN {name} over the log-mel patch, through nn_infer.", provenance)
    return f"""{head}
#include "classifier.h"
#include "dsp_config.h"
#include "models.h"

#include "nn_infer.h"
#include "nn_model_data_{name}.h"

_Static_assert(NN_MACS_{up} <= {mac_budget}u,
               "{name} exceeds the multiply-accumulate budget for one window");

/* Two activation buffers, static: at up to NN_MAX_ACT floats each they are far
   too big for the superloop's stack, and the detector runs one window at a time. */
static float s_act_a[NN_MAX_ACT_{up}];
static float s_act_b[NN_MAX_ACT_{up}];

static float decide(void *ctx, const float *features, uint16_t n)
{{
    (void)ctx;
    float out = 0.0f;
    if (n != {width_macro})
    {{
        return 0.0f;
    }}
    (void)nn_forward(&nn_net_{name}, features, s_act_a, s_act_b, &out);
    return out;
}}

const classifier_t classifier_{name} = {{
    .name              = "{name}",
    .layout_id         = {layout_macro},
    .n_features        = {width_macro},
    .feature_offset    = 0u,
    .default_thr_milli = {thr_milli},
    .decide            = decide,
    .ctx               = NULL,
}};
"""


def registry_lines(names: list[str]) -> tuple[str, str]:
    """What to paste into models/models.h and src/classifier_registry.c."""
    decls = "\n".join(f"extern const classifier_t classifier_{n};" for n in names)
    entries = "\n".join(f"    &classifier_{n}," for n in names)
    return decls, entries


def thr_milli_from(threshold: float) -> int:
    return int(np.round(float(threshold) * 1000.0))
