"""Write models as the C headers the translation units under models/ include.

Three table formats, one per family the C knows how to run:

* MLP: scaler, one hidden ReLU layer, linear output - the format
  models/mlp_model_data_v6.h already has, so model_mlp_v6.c's forward pass
  runs any exported MLP unchanged. Only the dimensions differ.
* linear: scaler, weights, bias - models/svm_model_data_v3.h's format.
* GBT: a forest as flat node arrays. Each tree is a contiguous run of nodes;
  a node with feature 0xFF is a leaf and its value is added to the sum. Split
  nodes send x[feature] <= threshold left, which is scikit-learn's
  HistGradientBoosting convention (its thresholds are midpoints between
  training values, so equality is a non-event).

Every header also gets its parity vectors: PARITY_N windows of real features
and the decision Python computed for them in float32. The C test
model_parity_test reads those and holds the two implementations together.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np

from boomdetect_train.features import LAYOUTS
from boomdetect_train.train import ScaledModel

PARITY_N = 16


def _c_float(v: float) -> str:
    """Shortest repr that round-trips through float32, with the f suffix."""
    f = float(np.float32(v))
    s = f"{f:.9g}"
    if "e" not in s and "." not in s and "inf" not in s and "nan" not in s:
        s += ".0"
    return s + "f"


def _chunks(tokens: list[str], per_line: int = 8, indent: str = "    ") -> list[str]:
    return [
        indent + ", ".join(tokens[i : i + per_line]) + "," for i in range(0, len(tokens), per_line)
    ]


def _c_array(name: str, ctype: str, values: np.ndarray, dims: tuple[int, ...], fmt) -> str:
    """`static const <ctype> name[d0][d1] = { ... };` with 8 values per line.

    A 2-D array gets one braced row per leading index: gcc's -Wmissing-braces
    (on under -Wall, fatal under -Werror) rejects a flat initializer for it.
    """
    arr = np.asarray(values)
    dim_str = "".join(f"[{d}]" for d in dims)
    lines = [f"static const {ctype} {name}{dim_str} = {{"]
    if len(dims) == 2:
        for r in arr.reshape(dims):
            lines.append("    {")
            lines += _chunks([fmt(v) for v in r], indent="        ")
            lines.append("    },")
    else:
        lines += _chunks([fmt(v) for v in arr.reshape(-1)])
    lines.append("};")
    return "\n".join(lines)


def _header(guard: str, title: str, provenance: list[str]) -> list[str]:
    lines = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "/*",
        f" * {title}",
        " *",
        " * GENERATED by fw/common/boomdetect/training (bdtrain export); do not edit.",
    ]
    for p in provenance:
        lines.append(f" * {p}")
    lines += [" */", "", "#include <stdint.h>", ""]
    return lines


@dataclass
class ParityVectors:
    features: np.ndarray  # (n, n_features_full) float32, the FULL layout vector
    expected: np.ndarray  # (n,) float32 decisions from the Python forward pass


def parity_vectors(
    model: ScaledModel, x_full: np.ndarray, n: int = PARITY_N, seed: int = 7
) -> ParityVectors:
    """Pick `n` real windows spread over the score range and score them in Python."""
    rng = np.random.default_rng(seed)
    if x_full.shape[0] <= n:
        pick = np.arange(x_full.shape[0])
    else:
        scores = model.score(x_full)
        order = np.argsort(scores)
        # Quantiles of the score distribution plus a few random ones: the
        # extremes are where a saturating or overflowing implementation shows.
        q = order[np.linspace(0, order.size - 1, max(n - 4, 2)).astype(int)]
        r = rng.choice(order, size=n - q.size, replace=False)
        pick = np.unique(np.concatenate([q, r]))[:n]
    feats = np.asarray(x_full[pick], dtype=np.float32)
    return ParityVectors(feats, np.asarray(model.score(feats), dtype=np.float32).reshape(-1))


def export_mlp(model: ScaledModel, tag: str, provenance: list[str]) -> str:
    clf = model.model
    w1 = clf.coefs_[0].T.astype(np.float32)  # (hidden, inputs)
    b1 = clf.intercepts_[0].astype(np.float32)
    w2 = clf.coefs_[1][:, 0].astype(np.float32)
    b2 = float(clf.intercepts_[1][0])
    hidden, inputs = w1.shape
    guard = f"MLP_MODEL_DATA_{tag.upper()}_H"
    lines = _header(guard, f"MLP {tag}: {inputs} -> {hidden} -> 1, ReLU, logit output", provenance)
    lines += [
        f"#define MLP_NUM_INPUTS {inputs}",
        f"#define MLP_HIDDEN {hidden}",
        f"#define MLP_B2 {_c_float(b2)}",
        "",
        _c_array("mlp_scaler_mean", "float", model.scaler_mean, (inputs,), _c_float),
        "",
        _c_array("mlp_scaler_inv_std", "float", model.scaler_inv_std, (inputs,), _c_float),
        "",
        _c_array("mlp_w1", "float", w1, (hidden, inputs), _c_float),
        "",
        _c_array("mlp_b1", "float", b1, (hidden,), _c_float),
        "",
        _c_array("mlp_w2", "float", w2, (hidden,), _c_float),
        "",
        f"#endif /* {guard} */",
        "",
    ]
    return "\n".join(lines)


def export_linear(model: ScaledModel, tag: str, provenance: list[str]) -> str:
    clf = model.model
    w = clf.coef_[0].astype(np.float32)
    b = float(clf.intercept_[0])
    n = w.shape[0]
    guard = f"SVM_MODEL_DATA_{tag.upper()}_H"
    lines = _header(
        guard, f"Linear SVM {tag}: {n} standardised features, margin output", provenance
    )
    lines += [
        f"#define SVM_NUM_FEATURES {n}",
        f"#define SVM_BIAS {_c_float(b)}",
        "",
        _c_array("svm_scaler_mean", "float", model.scaler_mean, (n,), _c_float),
        "",
        _c_array("svm_scaler_inv_std", "float", model.scaler_inv_std, (n,), _c_float),
        "",
        _c_array("svm_weights", "float", w, (n,), _c_float),
        "",
        f"#endif /* {guard} */",
        "",
    ]
    return "\n".join(lines)


GBT_LEAF = 0xFF


def flatten_forest(clf) -> dict[str, np.ndarray]:
    """HistGradientBoosting's per-tree node records as flat arrays, trees back to back."""
    roots, feat, thr, left, right, value = [], [], [], [], [], []
    base = 0
    for predictors in clf._predictors:
        nodes = predictors[0].nodes
        roots.append(base)
        for nd in nodes:
            if nd["is_leaf"]:
                feat.append(GBT_LEAF)
                thr.append(0.0)
                left.append(0)
                right.append(0)
                value.append(float(nd["value"]))
            else:
                if nd["is_categorical"]:
                    raise ValueError("categorical splits are not exportable")
                feat.append(int(nd["feature_idx"]))
                thr.append(float(nd["num_threshold"]))
                left.append(int(nd["left"]) + base)
                right.append(int(nd["right"]) + base)
                value.append(0.0)
        base += len(nodes)
    return {
        "roots": np.asarray(roots, dtype=np.int64),
        "feature": np.asarray(feat, dtype=np.int64),
        "threshold": np.asarray(thr, dtype=np.float32),
        "left": np.asarray(left, dtype=np.int64),
        "right": np.asarray(right, dtype=np.int64),
        "value": np.asarray(value, dtype=np.float32),
        "baseline": np.float32(clf._baseline_prediction.reshape(-1)[0]),
    }


def forest_decision(flat: dict[str, np.ndarray], x: np.ndarray) -> np.ndarray:
    """Evaluate the flattened forest exactly as the C will, in float32."""
    x = np.atleast_2d(np.asarray(x, dtype=np.float32))
    out = np.full(x.shape[0], flat["baseline"], dtype=np.float32)
    for i in range(x.shape[0]):
        acc = np.float32(flat["baseline"])
        for root in flat["roots"]:
            n = int(root)
            while flat["feature"][n] != GBT_LEAF:
                f = int(flat["feature"][n])
                n = (
                    int(flat["left"][n])
                    if x[i, f] <= flat["threshold"][n]
                    else int(flat["right"][n])
                )
            acc = np.float32(acc + flat["value"][n])
        out[i] = acc
    return out


def export_gbt(model: ScaledModel, tag: str, provenance: list[str]) -> str:
    flat = flatten_forest(model.model)
    n_nodes = flat["feature"].shape[0]
    n_trees = flat["roots"].shape[0]
    n_feat = model.n_features
    if n_nodes >= 0xFFFF:
        raise ValueError("forest too large for uint16 node indices")
    guard = f"GBT_MODEL_DATA_{tag.upper()}_H"
    lines = _header(
        guard,
        f"Gradient-boosted trees {tag}: {n_trees} trees, {n_nodes} nodes, {n_feat} features, "
        "log-odds output",
        provenance,
    )
    lines += [
        f"#define GBT_NUM_FEATURES {n_feat}",
        f"#define GBT_NUM_TREES {n_trees}",
        f"#define GBT_NUM_NODES {n_nodes}",
        f"#define GBT_LEAF {GBT_LEAF}u",
        f"#define GBT_BASELINE {_c_float(float(flat['baseline']))}",
        "",
        _c_array("gbt_tree_root", "uint16_t", flat["roots"], (n_trees,), lambda v: f"{int(v)}u"),
        "",
        _c_array(
            "gbt_node_feature", "uint8_t", flat["feature"], (n_nodes,), lambda v: f"{int(v)}u"
        ),
        "",
        _c_array("gbt_node_threshold", "float", flat["threshold"], (n_nodes,), _c_float),
        "",
        _c_array("gbt_node_left", "uint16_t", flat["left"], (n_nodes,), lambda v: f"{int(v)}u"),
        "",
        _c_array("gbt_node_right", "uint16_t", flat["right"], (n_nodes,), lambda v: f"{int(v)}u"),
        "",
        _c_array("gbt_node_value", "float", flat["value"], (n_nodes,), _c_float),
        "",
        f"#endif /* {guard} */",
        "",
    ]
    return "\n".join(lines)


def export_model(model: ScaledModel, tag: str, provenance: list[str]) -> str:
    if model.kind == "mlp":
        return export_mlp(model, tag, provenance)
    if model.kind == "svm":
        return export_linear(model, tag, provenance)
    if model.kind == "gbt":
        return export_gbt(model, tag, provenance)
    raise ValueError(model.kind)


def export_parity_block(name: str, layout: int, offset: int, vectors: ParityVectors) -> str:
    """The C for one model's parity vectors: full-layout features and expected decisions."""
    n, width = vectors.features.shape
    assert width == LAYOUTS[layout].n_features
    ident = name.replace("-", "_")
    return "\n".join(
        [
            f"/* {name}: layout {layout} ({LAYOUTS[layout].name}), offset {offset} */",
            _c_array(f"parity_{ident}_features", "float", vectors.features, (n, width), _c_float),
            _c_array(f"parity_{ident}_expected", "float", vectors.expected, (n,), _c_float),
        ]
    )


def export_parity_header(
    entries: list[tuple[str, int, int, ParityVectors]], provenance: list[str]
) -> str:
    """tests/vectors/parity_vectors.h: every model's vectors plus a table to iterate."""
    guard = "BOOMDETECT_PARITY_VECTORS_H"
    lines = _header(guard, "Python-versus-C parity vectors for every registered model", provenance)
    lines += [
        "typedef struct",
        "{",
        "    const char  *name;",
        "    uint16_t     layout_id;",
        "    uint16_t     n_features;   /* full layout width */",
        "    uint16_t     n_vectors;",
        "    const float *features;     /* n_vectors x n_features */",
        "    const float *expected;     /* n_vectors */",
        "} parity_entry_t;",
        "",
    ]
    for name, layout, offset, vec in entries:
        lines += [export_parity_block(name, layout, offset, vec), ""]
    lines.append("static const parity_entry_t parity_entries[] = {")
    for name, layout, _offset, vec in entries:
        ident = name.replace("-", "_")
        n, width = vec.features.shape
        lines.append(
            f'    {{ "{name}", {layout}u, {width}u, {n}u, &parity_{ident}_features[0][0], '
            f"parity_{ident}_expected }},"
        )
    lines += ["};", "", f"#endif /* {guard} */", ""]
    return "\n".join(lines)


def write_text(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return path
