services:
  fw-devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/fw-devcontainer/Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - ../:/workspace:cached
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: sleep infinity

  sw-devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/sw-devcontainer/Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - ../:/workspace:cached
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: sleep infinity
