#ifndef FXLMS_FILTER_H
#define FXLMS_FILTER_H

/**
 * @file lms_filter.h
 * @brief Fixed-point filtered-x LMS active-noise-control demo core.
 *
 * The demo models this ANC topology:
 *
 *   x[n] -> P(z) -> d[n]
 *   x[n] -> G(z) -> y[n] -> C(z) -> secondary[n]
 *   e[n] = d[n] - secondary[n]
 *   x_filtered[n] = C_hat(z) * x[n]
 *   g_i[n + 1] = g_i[n] + (mu / P[n]) * e[n] * x_filtered[n - i]
 *
 * The step uses a normalized (NLMS-style) learning rate: `mu` is divided by the
 * instantaneous filtered-x power `P[n] = eps + sum |x_filtered[n - i]|^2`, where
 * the sum runs over all taps and all reference/actuator channels. This makes the
 * effective step independent of the input level and of the number of channels,
 * so the same `mu` works for SISO and multi-channel configurations.
 *
 * `P(z)` is generated by the Python harness. `G(z)` is the adaptive FIR
 * controller in this C core. `C(z)` is a fixed demo secondary path in this C
 * core. `C_hat(z)` is a similar, non-identical secondary-path estimate used
 * only by the filtered-x adaptation branch.
 *
 * All FIRs use newest-sample-first tap order: tap `i` multiplies sample
 * `n - i`. Public samples and coefficients use signed Q15-like PCM
 * (`int16_t`) centered around zero. The core API does not allocate heap memory;
 * callers provide a state buffer sized by `fxlms_state_size()`.
 */

#include <stddef.h>
#include <stdint.h>

#if __has_include("fxlms_config.h")
#include "fxlms_config.h"
#elif __has_include("lms_config.h")
#include "lms_config.h"
#endif

#ifndef CONFIG_FXLMS_TAPS
#ifdef CONFIG_LMS_TAPS
#define CONFIG_FXLMS_TAPS CONFIG_LMS_TAPS
#else
#define CONFIG_FXLMS_TAPS 64
#endif
#endif

#ifndef CONFIG_FXLMS_MU_Q15
#ifdef CONFIG_LMS_MU_Q15
#define CONFIG_FXLMS_MU_Q15 CONFIG_LMS_MU_Q15
#else
#define CONFIG_FXLMS_MU_Q15 64
#endif
#endif

#ifndef CONFIG_FXLMS_ADAPT_SHIFT
#ifdef CONFIG_LMS_ADAPT_SHIFT
#define CONFIG_FXLMS_ADAPT_SHIFT CONFIG_LMS_ADAPT_SHIFT
#else
#define CONFIG_FXLMS_ADAPT_SHIFT 0
#endif
#endif

#ifndef CONFIG_FXLMS_OUTPUT_LIMIT
#ifdef CONFIG_LMS_OUTPUT_LIMIT
#define CONFIG_FXLMS_OUTPUT_LIMIT CONFIG_LMS_OUTPUT_LIMIT
#else
#define CONFIG_FXLMS_OUTPUT_LIMIT 32767
#endif
#endif

/*
 * Regularization floor for the normalized (NLMS-style) step size, expressed as
 * a per-(channel, tap) energy added to the filtered-x power in the update
 * denominator. It keeps the step finite when the reference is silent and is
 * negligible relative to the filtered-x power during normal operation.
 */
#ifndef CONFIG_FXLMS_NLMS_POWER_FLOOR
#define CONFIG_FXLMS_NLMS_POWER_FLOOR 256
#endif

#ifndef CONFIG_FXLMS_MAX_REFERENCES
#define CONFIG_FXLMS_MAX_REFERENCES 4
#endif

#ifndef CONFIG_FXLMS_MAX_ACTUATORS
#define CONFIG_FXLMS_MAX_ACTUATORS 4
#endif

#if CONFIG_FXLMS_MAX_REFERENCES < 1 || CONFIG_FXLMS_MAX_REFERENCES > 4
#error "CONFIG_FXLMS_MAX_REFERENCES must be in range 1..4"
#endif

#if CONFIG_FXLMS_MAX_ACTUATORS < 1 || CONFIG_FXLMS_MAX_ACTUATORS > 4
#error "CONFIG_FXLMS_MAX_ACTUATORS must be in range 1..4"
#endif

#ifdef __cplusplus
extern "C" {
#endif

enum fxlms_status {
  FXLMS_OK = 0,
  FXLMS_ERR_INVALID_ARG = -1,
  FXLMS_ERR_BUFFER_TOO_SMALL = -2,
  FXLMS_ERR_INVALID_CONFIG = -3
};

struct fxlms_config {
  /** Number of adaptive FIR taps in G(z). */
  uint16_t taps;
  /** Number of reference inputs. `0` is treated as legacy SISO `1`. */
  uint8_t reference_count;
  /** Number of actuator/controller outputs. `0` is treated as legacy SISO `1`. */
  uint8_t actuator_count;
  /** Normalized learning rate in Q15 (0..1.0). `0` disables adaptation.
   *  Interpreted as the dimensionless NLMS step; the update divides it by the
   *  filtered-x power, so it is independent of input level and channel count. */
  int16_t mu_q15;
  /** Optional extra right shift on the (already normalized) weight update. */
  uint8_t adapt_shift;
  /** Absolute saturation limit for public output samples. */
  int16_t output_limit;
};

struct fxlms_state;

struct fxlms_sample_result {
  /** Adaptive controller output y[n] = G(z) * x[n]. */
  int16_t controller_y;
  /** Demo secondary path output C(z) * y[n]. */
  int16_t secondary_output;
  /** Residual error e[n] = d[n] - C(z)y[n]. */
  int16_t error;
};

struct fxlms_multi_sample_result {
  /** Per-actuator adaptive controller outputs y_j[n]. */
  int16_t controller_y[CONFIG_FXLMS_MAX_ACTUATORS];
  /** Per-actuator demo secondary path outputs C_j(z) * y_j[n]. */
  int16_t secondary_output[CONFIG_FXLMS_MAX_ACTUATORS];
  /** Sum of all per-actuator secondary outputs. */
  int16_t secondary_sum;
  /** Residual error e[n] = d[n] - sum_j C_j(z)y_j[n]. */
  int16_t error;
};

struct fxlms_config fxlms_default_config(void);

int fxlms_state_size(const struct fxlms_config *cfg, size_t *out_size);

int fxlms_init(void *mem, size_t mem_size, const struct fxlms_config *cfg,
               struct fxlms_state **out);

int fxlms_reset(struct fxlms_state *state);

int fxlms_process_sample(struct fxlms_state *state, int16_t reference_x,
                         int16_t primary_d, struct fxlms_sample_result *out);

int fxlms_process_multi_sample(struct fxlms_state *state,
                               const int16_t *reference_x, int16_t primary_d,
                               struct fxlms_multi_sample_result *out);

int fxlms_process_block(struct fxlms_state *state, const int16_t *reference_x,
                        const int16_t *primary_d, int16_t *error_e,
                        int16_t *controller_y, int16_t *secondary_output,
                        size_t n);

/**
 * Multi-channel block API.
 *
 * `reference_x` is channel-major: reference r sample i is at
 * `reference_x[r * n + i]`. Optional `controller_y` and `secondary_output`
 * are also channel-major by actuator.
 */
int fxlms_process_multi_block(struct fxlms_state *state,
                              const int16_t *reference_x,
                              const int16_t *primary_d, int16_t *error_e,
                              int16_t *controller_y,
                              int16_t *secondary_output, size_t n);

/**
 * Host convenience wrapper that allocates state and processes one array.
 * Embedded code should generally use the no-heap state API above.
 */
int fxlms_filter_i16(const int16_t *reference_x, const int16_t *primary_d,
                     int16_t *error_e, int16_t *controller_y,
                     int16_t *secondary_output, size_t n);

int fxlms_filter_multi_i16(const int16_t *reference_x, const int16_t *primary_d,
                           uint8_t reference_count, uint8_t actuator_count,
                           int16_t *error_e, int16_t *controller_y,
                           int16_t *secondary_output, size_t n);

#ifdef FXLMS_TESTING
int fxlms_test_set_controller_tap(struct fxlms_state *state, uint16_t tap,
                                  int16_t value);
int fxlms_test_set_multi_controller_tap(struct fxlms_state *state,
                                        uint8_t actuator, uint8_t reference,
                                        uint16_t tap, int16_t value);
int fxlms_test_set_secondary_path(const int16_t *coeffs, size_t n);
int fxlms_test_set_secondary_estimate(const int16_t *coeffs, size_t n);
int fxlms_test_set_actuator_secondary_path(uint8_t actuator,
                                           const int16_t *coeffs, size_t n);
int fxlms_test_set_actuator_secondary_estimate(uint8_t actuator,
                                               const int16_t *coeffs, size_t n);
#endif

#ifdef __cplusplus
}
#endif

#endif /* FXLMS_FILTER_H */
