#ifndef FXLMS_FILTER_H
#define FXLMS_FILTER_H

/**
 * @file lms_filter.h
 * @brief Fixed-point filtered-x LMS active-noise-control demo core.
 *
 * The demo models this ANC topology:
 *
 *   x[n] -> P(z) -> d[n]
 *   x[n] -> G(z) -> y[n] -> C(z) -> secondary[n]
 *   e[n] = d[n] - secondary[n]
 *   x_filtered[n] = C_hat(z) * x[n]
 *   g_i[n + 1] = g_i[n] + mu * e[n] * x_filtered[n - i]
 *
 * `P(z)` is generated by the Python harness. `G(z)` is the adaptive FIR
 * controller in this C core. `C(z)` is a fixed demo secondary path in this C
 * core. `C_hat(z)` is a similar, non-identical secondary-path estimate used
 * only by the filtered-x adaptation branch.
 *
 * All FIRs use newest-sample-first tap order: tap `i` multiplies sample
 * `n - i`. Public samples and coefficients use signed Q15-like PCM
 * (`int16_t`) centered around zero. The core API does not allocate heap memory;
 * callers provide a state buffer sized by `fxlms_state_size()`.
 */

#include <stddef.h>
#include <stdint.h>

#if __has_include("fxlms_config.h")
#include "fxlms_config.h"
#elif __has_include("lms_config.h")
#include "lms_config.h"
#endif

#ifndef CONFIG_FXLMS_TAPS
#ifdef CONFIG_LMS_TAPS
#define CONFIG_FXLMS_TAPS CONFIG_LMS_TAPS
#else
#define CONFIG_FXLMS_TAPS 64
#endif
#endif

#ifndef CONFIG_FXLMS_MU_Q15
#ifdef CONFIG_LMS_MU_Q15
#define CONFIG_FXLMS_MU_Q15 CONFIG_LMS_MU_Q15
#else
#define CONFIG_FXLMS_MU_Q15 64
#endif
#endif

#ifndef CONFIG_FXLMS_ADAPT_SHIFT
#ifdef CONFIG_LMS_ADAPT_SHIFT
#define CONFIG_FXLMS_ADAPT_SHIFT CONFIG_LMS_ADAPT_SHIFT
#else
#define CONFIG_FXLMS_ADAPT_SHIFT 0
#endif
#endif

#ifndef CONFIG_FXLMS_OUTPUT_LIMIT
#ifdef CONFIG_LMS_OUTPUT_LIMIT
#define CONFIG_FXLMS_OUTPUT_LIMIT CONFIG_LMS_OUTPUT_LIMIT
#else
#define CONFIG_FXLMS_OUTPUT_LIMIT 32767
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

enum fxlms_status {
  FXLMS_OK = 0,
  FXLMS_ERR_INVALID_ARG = -1,
  FXLMS_ERR_BUFFER_TOO_SMALL = -2,
  FXLMS_ERR_INVALID_CONFIG = -3
};

struct fxlms_config {
  /** Number of adaptive FIR taps in G(z). */
  uint16_t taps;
  /** Learning rate in Q15. `0` disables adaptation and leaves G(z) fixed. */
  int16_t mu_q15;
  /** Extra right shift on the fixed-point controller-weight update. */
  uint8_t adapt_shift;
  /** Absolute saturation limit for public output samples. */
  int16_t output_limit;
};

struct fxlms_state;

struct fxlms_sample_result {
  /** Adaptive controller output y[n] = G(z) * x[n]. */
  int16_t controller_y;
  /** Demo secondary path output C(z) * y[n]. */
  int16_t secondary_output;
  /** Residual error e[n] = d[n] - C(z)y[n]. */
  int16_t error;
};

struct fxlms_config fxlms_default_config(void);

int fxlms_state_size(const struct fxlms_config *cfg, size_t *out_size);

int fxlms_init(void *mem, size_t mem_size, const struct fxlms_config *cfg,
               struct fxlms_state **out);

int fxlms_reset(struct fxlms_state *state);

int fxlms_process_sample(struct fxlms_state *state, int16_t reference_x,
                         int16_t primary_d, struct fxlms_sample_result *out);

int fxlms_process_block(struct fxlms_state *state, const int16_t *reference_x,
                        const int16_t *primary_d, int16_t *error_e,
                        int16_t *controller_y, int16_t *secondary_output,
                        size_t n);

/**
 * Host convenience wrapper that allocates state and processes one array.
 * Embedded code should generally use the no-heap state API above.
 */
int fxlms_filter_i16(const int16_t *reference_x, const int16_t *primary_d,
                     int16_t *error_e, int16_t *controller_y,
                     int16_t *secondary_output, size_t n);

#ifdef FXLMS_TESTING
int fxlms_test_set_controller_tap(struct fxlms_state *state, uint16_t tap,
                                  int16_t value);
int fxlms_test_set_secondary_path(const int16_t *coeffs, size_t n);
int fxlms_test_set_secondary_estimate(const int16_t *coeffs, size_t n);
#endif

#ifdef __cplusplus
}
#endif

#endif /* FXLMS_FILTER_H */
