/**
 * @file model_parity_test.c
 * @brief Every registered model against the decisions Python computed for it.
 *
 * tests/vectors/parity_vectors.h (generated by `bdtrain export`) carries, per
 * model, a handful of real feature vectors in the model's full layout and the
 * float32 decision the Python forward pass produced. This hands each vector to
 * the C forward pass through the registry - offset applied the way
 * boomdetect_step() applies it - and compares.
 *
 * The tolerance is for float32 summation order (a dot product in numpy and in
 * arm_dot_prod_f32 do not associate the same way), measured well under 1e-5 on
 * the shipped models; 1e-4 leaves room for a tree ensemble adding 200 leaf
 * values in a different order without letting a wrong weight through.
 */
#include "bd_test.h"
#include "classifier.h"
#include "extractor.h"
#include "vectors/parity_vectors.h"

#include <math.h>
#include <string.h>

BD_TEST_STATE;

#define PARITY_REL 1e-4f
#define PARITY_ABS 1e-4f

static void scenario_every_entry_has_a_model_and_vice_versa(void)
{
    const size_t n_entries = sizeof(parity_entries) / sizeof(parity_entries[0]);
    REQUIRE(n_entries >= 2u, "the parity header lists %u models", (unsigned)n_entries);
    for (size_t e = 0u; e < n_entries; e++)
    {
        const parity_entry_t *p = &parity_entries[e];
        CHECK(classifier_by_name(p->name) != NULL, "parity vectors exist for '%s' but no such model",
              p->name);
    }
    /* Every registered model must have vectors: a model without them is a
       model whose forward pass nothing checks. */
    for (size_t i = 0u; i < classifier_count(); i++)
    {
        const classifier_t *m = classifier_at(i);
        bool found = false;
        for (size_t e = 0u; e < n_entries; e++)
        {
            if (strcmp(parity_entries[e].name, m->name) == 0)
            {
                found = true;
            }
        }
        CHECK(found, "model '%s' has no parity vectors; regenerate with `bdtrain export`", m->name);
    }
}

static void scenario_decisions_match(void)
{
    const size_t n_entries = sizeof(parity_entries) / sizeof(parity_entries[0]);
    for (size_t e = 0u; e < n_entries; e++)
    {
        const parity_entry_t *p = &parity_entries[e];
        const classifier_t   *m = classifier_by_name(p->name);
        if (m == NULL)
        {
            continue; /* reported above */
        }
        const boomdetect_extractor_t *ex = boomdetect_extractor_for_layout(m->layout_id);
        REQUIRE(ex != NULL, "%s: no extractor for layout %u", p->name, m->layout_id);
        REQUIRE(p->layout_id == m->layout_id && p->n_features == ex->n_features,
                "%s: vectors are layout %u x %u, model is layout %u over %u", p->name, p->layout_id,
                p->n_features, m->layout_id, ex->n_features);
        REQUIRE((uint32_t)m->feature_offset + m->n_features <= p->n_features,
                "%s reads past the vector", p->name);

        float worst = 0.0f;
        for (uint16_t v = 0u; v < p->n_vectors; v++)
        {
            const float *feat = p->features + (size_t)v * p->n_features;
            const float  got  = m->decide(m->ctx, feat + m->feature_offset, m->n_features);
            const float  want = p->expected[v];
            const float  err  = fabsf(got - want);
            const float  tol  = PARITY_REL * fmaxf(fabsf(got), fabsf(want)) + PARITY_ABS;
            if (err > worst)
            {
                worst = err;
            }
            CHECK(isfinite(got), "%s vector %u: non-finite decision", p->name, v);
            CHECK(err <= tol, "%s vector %u: C %.9g, python %.9g (err %.3g > tol %.3g)", p->name, v,
                  (double)got, (double)want, (double)err, (double)tol);
        }
        printf("%-16s %2u vectors, worst |C - python| = %.3g\n", p->name, p->n_vectors, (double)worst);
    }
}

int main(void)
{
    scenario_every_entry_has_a_model_and_vice_versa();
    scenario_decisions_match();
    /* Exact count from running the compiled binary: six models x 16 vectors x 2
       checks plus the registry cross-checks. Re-read it off the binary whenever
       a model is added or removed. */
    BD_TEST_REPORT("model_parity_test", 223);
}
