version: "3"

includes:
  median-filter:
    taskfile: ./median-filter/Taskfile.yml
    dir: ./median-filter
    optional: true

tasks:
  benchmark:
    desc: Run median-filter benchmark
    cmds:
      - task median-filter:benchmark
