"""Analytical operation count of the localisation methods for a 100 ms segment.

The count follows what an MCU implementation of each method in :mod:`beamforming.doa` has to
do, in real multiply-accumulates (MAC). It is an order-of-magnitude estimate for choosing a
method, not a measurement; the final budget for the chosen method belongs to the firmware
sizing. Conventions:

* one complex MAC is 4 real MAC, a real-input FFT of ``n`` points ``n log2 n`` MAC,
* ``sqrt`` or division is ``SQRT_DIV_MAC`` MAC, one ``sin``/``cos`` pair ``SINCOS_MAC`` MAC,
* steering vectors are generated by a phase recurrence over the bins (two sin/cos pairs per
  microphone and direction, then one complex multiplication per bin),
* covariances use the Hermitian symmetry, MVDR inverts ``R`` once per bin (Cholesky, ``M^3``
  complex MAC) and evaluates ``a^H R^-1 a`` per direction, MUSIC needs ``n_src`` eigenvectors
  of ``R`` (about ``EIG_MAC_PER_M3 * M^3`` MAC per bin),
* GCC-PHAT correlates every pair and interpolates the lag by a zero-padded inverse FFT
  ``gcc_upsample`` times finer, as the simulation does,
* the time estimate assumes ``CYCLES_PER_MAC`` core cycles per MAC (loads and loop overhead
  included) at ``F_CPU_HZ``; it is an assumption to be replaced by a measurement.

MVDR could use the rank of ``R`` (at most the T frames) through the Woodbury identity and
MUSIC a power iteration, so both counts are upper bounds for a direct implementation.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from . import doa
from . import geometry as g
from . import signals as sg

CMAC = 4
SQRT_DIV_MAC = 10
SINCOS_MAC = 40
EIG_MAC_PER_M3 = 10
CYCLES_PER_MAC = 2.0
F_CPU_HZ = 250e6
N_MICS = 16


def fft_real(n: int) -> float:
    """Real-input (or real-output) FFT of ``n`` points."""
    return n * float(np.log2(n))


@dataclass(frozen=True)
class Workload:
    """Sizes of one localisation (defaults: report configuration, 100 ms at 16 kHz)."""

    M: int = N_MICS
    T: int = 5  # STFT frames
    nfft: int = sg.NFFT
    n_samples: int = sg.SEGMENT
    K: int = 55  # bins of the band
    d_coarse: int = 1368
    d_fine: int = 121
    n_src: int = 1
    gcc_upsample: int = 16
    gcc_band_bins: int = 341  # bins of the band in the 2 * n_samples point GCC spectrum

    @property
    def D(self) -> int:
        return self.d_coarse + self.d_fine

    @property
    def pairs(self) -> int:
        return self.M * (self.M - 1) // 2

    @classmethod
    def from_config(
        cls, cfg: doa.Config = doa.DEFAULT, n_mics: int = N_MICS, n_samples: int = sg.SEGMENT
    ) -> Workload:
        """Sizes implied by a processing configuration."""
        bins = len(sg.band_bins(cfg.fs, cfg.nfft, cfg.band)) - 2 * cfg.guard_bins
        n_fine = int(round(cfg.fine_span / cfg.fine_step))  # as geometry.fine_cap
        df_gcc = cfg.fs / (2 * n_samples)
        return cls(
            M=n_mics,
            T=1 + (n_samples - cfg.nfft) // cfg.hop,
            nfft=cfg.nfft,
            n_samples=n_samples,
            K=bins,
            d_coarse=int(np.prod(g.grid_shape(cfg.coarse_step))),
            d_fine=(2 * n_fine + 1) ** 2,
            n_src=cfg.n_src,
            gcc_upsample=cfg.gcc_upsample,
            gcc_band_bins=int(np.floor(cfg.band[1] / df_gcc) - np.ceil(cfg.band[0] / df_gcc) + 1),
        )


@dataclass(frozen=True)
class Cost:
    """Operation count in real MAC split by stage (sin/cos pairs weighted by ``SINCOS_MAC``)."""

    parts: dict[str, float] = field(default_factory=dict)

    @property
    def mac(self) -> float:
        return float(sum(self.parts.values()))

    def time_s(self, cycles_per_mac: float = CYCLES_PER_MAC, f_cpu_hz: float = F_CPU_HZ) -> float:
        return self.mac * cycles_per_mac / f_cpu_hz


def _stft(w: Workload) -> float:
    return w.M * w.T * (fft_real(w.nfft) + w.nfft)  # FFT and the Hann window


def _steering(w: Workload) -> float:
    delays = 3.0 * w.M * w.D  # r . u per microphone and direction
    sincos = 2.0 * w.M * w.D * SINCOS_MAC
    recurrence = w.M * w.D * w.K * CMAC
    return delays + sincos + recurrence


def _beamform(w: Workload) -> float:
    """``Y = a^H X`` and ``|Y|^2`` for every bin, direction and frame, then the bin sum."""
    return w.K * w.D * w.T * (CMAC * w.M + 2) + w.K * w.D


def _covariance(w: Workload) -> float:
    return w.K * (w.M * (w.M + 1) // 2) * w.T * CMAC


def das(w: Workload) -> Cost:
    return Cost({"stft": _stft(w), "steering": _steering(w), "beamform": _beamform(w)})


def srp_phat(w: Workload) -> Cost:
    phat = w.M * w.K * w.T * (2 + 2 * SQRT_DIV_MAC)  # |X|^2, sqrt and the division
    return Cost(
        {"stft": _stft(w), "phat": phat, "steering": _steering(w), "beamform": _beamform(w)}
    )


def mvdr(w: Workload) -> Cost:
    inverse = w.K * CMAC * w.M**3
    quad = w.K * w.D * (w.M * w.M + w.M) * CMAC + w.K * w.D  # R^-1 a, a^H (R^-1 a), bin sum
    return Cost(
        {
            "stft": _stft(w),
            "covariance": _covariance(w),
            "inverse": inverse,
            "steering": _steering(w),
            "quadratic form": quad,
        }
    )


def music(w: Workload) -> Cost:
    eig = w.K * EIG_MAC_PER_M3 * w.M**3
    proj = w.K * w.D * w.n_src * (CMAC * w.M + 2) + w.K * w.D  # E_s^H a, |.|^2, bin sum
    return Cost(
        {
            "stft": _stft(w),
            "covariance": _covariance(w),
            "eigendecomposition": eig,
            "steering": _steering(w),
            "projection": proj,
        }
    )


def gcc_phat_ls(w: Workload) -> Cost:
    nz = 2 * w.n_samples
    big = nz * w.gcc_upsample
    max_lag = 2 * 100 + 1  # about +-100 interpolated lags for the longest pairs at 16x
    return Cost(
        {
            "fft": w.M * fft_real(nz),
            "cross spectra": w.pairs * w.gcc_band_bins * (CMAC + 2 * SQRT_DIV_MAC),
            "inverse fft": w.pairs * fft_real(big),
            "peak search": float(w.pairs * max_lag),
            "least squares": float(w.pairs * 3 * 3 + 100),
        }
    )


COSTS = {"das": das, "mvdr": mvdr, "srp_phat": srp_phat, "gcc_phat_ls": gcc_phat_ls, "music": music}


def cost(method: str, w: Workload | None = None) -> Cost:
    """Operation count of ``method`` (a name of :data:`beamforming.doa.METHODS`)."""
    if method not in COSTS:
        raise ValueError(f"unknown method {method!r}, expected one of {tuple(COSTS)}")
    return COSTS[method](Workload() if w is None else w)
