"""Render ``PROTOCOL.md`` from the declarative protocol spec.

Run via ``task proto`` (or ``python -m stm32node_cli.protocol.gen_docs``). The
generated file is the contract the STM32 firmware must implement; a test
(``tests/test_protocol_docs.py``) fails if it drifts from the spec.
"""

from __future__ import annotations

from pathlib import Path

from . import spec

# PROTOCOL.md lives at the project root: src/stm32node_cli/protocol/gen_docs.py
# -> parents[3] is the package root (.../stm32node-cli).
PROTOCOL_MD = Path(__file__).resolve().parents[3] / "PROTOCOL.md"


def _header_table() -> str:
    lines = [
        "| Offset | Field | C type | Description |",
        "|-------:|-------|--------|-------------|",
    ]
    offset = 0
    for f in spec.HEADER_FIELDS:
        size = spec.struct.calcsize("<" + f.fmt)
        lines.append(f"| {offset} | `{f.name}` | `{f.ctype}` | {f.description} |")
        offset += size
    return "\n".join(lines)


def _commands_section() -> str:
    blocks = []
    for c in spec.COMMANDS:
        blocks.append(
            f"### `{c.usage}`\n\n"
            f"{c.description}\n\n"
            f"**Response:** {c.response}"
        )
    return "\n\n".join(blocks)


def render() -> str:
    """Return the full Markdown document as a string."""
    return f"""<!-- GENERATED by stm32node_cli.protocol.gen_docs - do not edit by hand. -->
# STM32 node serial protocol

Contract between the `stm32node-cli` host tool and the `bom-stm32node` firmware,
spoken over the USB CDC ACM virtual COM port. This file is generated from
`src/stm32node_cli/protocol/spec.py`; run `task proto` to regenerate it.

## Audio format

- Sample rate: **{spec.SAMPLE_RATE_HZ} Hz**
- Channels: **{spec.CHANNELS}** (mono)
- Sample format: **{spec.SAMPLE_WIDTH_BYTES * 8}-bit signed, little-endian**

The host performs no DSP; the board sends finished PCM.

## Command channel (text)

Commands are ASCII lines terminated by `{spec.LINE_TERMINATOR!r}`. The board may
echo input and print a `> ` prompt.

{_commands_section()}

## Binary stream framing (`PCM1`)

`stream <sec>` triggers a binary transfer: a fixed **{spec.HEADER_SIZE}-byte**
little-endian header, immediately followed by exactly `byte_length` bytes of raw
PCM. The transfer is length-delimited (no trailer). The host resyncs to the
`{spec.MAGIC.decode()}` magic to skip any echoed text before the header.

### Header layout (protocol version {spec.PROTOCOL_VERSION})

{_header_table()}

`byte_length` equals `sec * {spec.SAMPLE_RATE_HZ} * {spec.SAMPLE_WIDTH_BYTES}`
for a `{spec.CHANNELS}`-channel stream.
"""


def write(path: Path = PROTOCOL_MD) -> Path:
    """Write the rendered document to ``path`` and return it."""
    path.write_text(render(), encoding="utf-8")
    return path


def main() -> None:
    out = write()
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
