/**
 * @file model_gbt_f1.c
 * @brief Gradient-boosted trees gbt_f1: a forest walk, log-odds output.
 *
 * GENERATED by fw/common/boomdetect/training (bdtrain export); do not edit.
 * Registered by hand in models/models.h and src/classifier_registry.c.
 * run: fw_aug
 * generated: 2026-09-26T16:28:19
 * family: gbt
 * layout: 2
 * default threshold: 2.646 (<= 5 FA/h on val at squelch 0.003)
 * trained as: gbt_reg_l2
 */
#include "classifier.h"
#include "dsp_config.h"
#include "models.h"

#include "gbt_model_data_gbt_f1.h"

#define OFFSET 1u

_Static_assert(OFFSET + GBT_NUM_FEATURES <= BOOMDETECT_FEATURE_COUNT_STATS_SPECTRAL,
               "gbt_f1's slice runs past the features its layout produces");

/* No scaler: a tree compares each feature against thresholds learned on the raw
   value, so standardising would only move the thresholds. Each tree is walked
   from its root until a leaf (feature GBT_LEAF); the leaf values sum onto the
   baseline log-odds. x <= threshold goes left, scikit-learn's convention. */
static float decide(void *ctx, const float *features, uint16_t n)
{
    (void)n;
    (void)ctx;
    float acc = GBT_BASELINE;
    for (uint32_t t = 0u; t < GBT_NUM_TREES; t++)
    {
        uint32_t node = gbt_tree_root[t];
        /* Bounded by the node count: a corrupt table cannot loop forever. */
        for (uint32_t guard = 0u; guard < GBT_NUM_NODES; guard++)
        {
            const uint8_t f = gbt_node_feature[node];
            if (f == GBT_LEAF)
            {
                break;
            }
            node = (features[f] <= gbt_node_threshold[node]) ? gbt_node_left[node]
                                                            : gbt_node_right[node];
        }
        acc += gbt_node_value[node];
    }
    return acc;
}

const classifier_t classifier_gbt_f1 = {
    .name              = "gbt_f1",
    .layout_id         = BOOMDETECT_LAYOUT_STATS_SPECTRAL,
    .n_features        = GBT_NUM_FEATURES,
    .feature_offset    = OFFSET,
    .default_thr_milli = 2646,
    .decide            = decide,
    .ctx               = NULL,
};
