/**
 * @file model_mlp_f2.c
 * @brief MLP mlp_f2: scaler, two hidden ReLU layers, logit output.
 *
 * GENERATED by fw/common/boomdetect/training (bdtrain export); do not edit.
 * Registered by hand in models/models.h and src/classifier_registry.c.
 * run: fw2_mlp2
 * generated: 2026-10-01T14:54:13
 * family: mlp
 * layout: 2
 * default threshold: 15.855 (<= 1 FA/h on val at squelch 0.003)
 * trained as: mlp2_l2
 */
#include "classifier.h"
#include "dsp_config.h"
#include "models.h"

#include "arm_math.h"
#include "mlp_model_data_mlp_f2.h"

#define OFFSET 1u

_Static_assert(OFFSET + MLP_NUM_INPUTS == BOOMDETECT_FEATURE_COUNT_STATS_SPECTRAL,
               "mlp_f2's slice does not cover the features its layout produces");

static float decide(void *ctx, const float *features, uint16_t n)
{
    (void)n;
    (void)ctx;
    float32_t x[MLP_NUM_INPUTS];
    float32_t h1[MLP_HIDDEN];
    float32_t h2[MLP_HIDDEN2];
    for (uint32_t i = 0u; i < MLP_NUM_INPUTS; i++)
    {
        x[i] = (features[i] - mlp_scaler_mean[i]) * mlp_scaler_inv_std[i];
    }
    for (uint32_t j = 0u; j < MLP_HIDDEN; j++)
    {
        float32_t acc = 0.0f;
        arm_dot_prod_f32(x, mlp_w1[j], MLP_NUM_INPUTS, &acc);
        acc += mlp_b1[j];
        h1[j] = (acc > 0.0f) ? acc : 0.0f;
    }
    for (uint32_t k = 0u; k < MLP_HIDDEN2; k++)
    {
        float32_t acc = 0.0f;
        arm_dot_prod_f32(h1, mlp_w2[k], MLP_HIDDEN, &acc);
        acc += mlp_b2[k];
        h2[k] = (acc > 0.0f) ? acc : 0.0f;
    }
    float32_t out = 0.0f;
    arm_dot_prod_f32(h2, mlp_w3, MLP_HIDDEN2, &out);
    return out + MLP_B3;
}

const classifier_t classifier_mlp_f2 = {
    .name              = "mlp_f2",
    .layout_id         = BOOMDETECT_LAYOUT_STATS_SPECTRAL,
    .n_features        = MLP_NUM_INPUTS,
    .feature_offset    = OFFSET,
    .default_thr_milli = 15855,
    .decide            = decide,
    .ctx               = NULL,
};
