/**
 * @file models.h
 * @brief Every classifier_t this package's models/ directory exports.
 *
 * The registry used to carry these as bare `extern` declarations inside its own
 * .c file, which means nothing ever cross-checked them against the definitions:
 * a model file renaming its entry, or giving it a different type, would fail at
 * link time with a symbol name rather than at compile time with the mismatch.
 * Both sides include this instead.
 *
 * Adding a model is still two edits and no more: a file here, and a line in
 * src/classifier_registry.c - plus this declaration, which is what makes the
 * compiler check the pair.
 */
#ifndef BOOMDETECT_MODELS_H
#define BOOMDETECT_MODELS_H

#include "classifier.h"

extern const classifier_t classifier_mlp_v6;
extern const classifier_t classifier_svm_v3;

/* Generated by `bdtrain export` from training run `full` (2026-09-23), trained
   on the whole 61-hour HuggingFace set with the split drawn on recording
   groups. One model per family worth carrying, so the board can score the same
   audio with each. The two linear SVMs of the previous set are gone: retrained
   on this much data they call almost nothing a drone (window TPR 0.00 and 0.08
   on the held-out third).

   Not deployed: the default stays mlp_v6 until field recordings decide. mlp_l2
   is the candidate to replace it - it detects 95 % of held-out drone windows
   against mlp_v6's 42 % at the same false-alarm budget, and alarms on 9 of 9
   Salford flyovers against 1 of 9 - but mlp_v6 still holds the best window AUC
   on Halmstad (0.937 against 0.715), which is the closest thing here to a
   microphone the models have never heard. */
extern const classifier_t classifier_mlp_l2;
extern const classifier_t classifier_gbt_l2;
extern const classifier_t classifier_gbt_reg_l2;
extern const classifier_t classifier_cnn_small;

#endif /* BOOMDETECT_MODELS_H */
