/**
 * @file model_cnn_small.c
 * @brief CNN cnn_small over the log-mel patch, through nn_infer.
 *
 * GENERATED by fw/common/boomdetect/training (bdtrain export); do not edit.
 * Registered by hand in models/models.h and src/classifier_registry.c.
 * run: r2
 * generated: 2026-09-06T20:52:44
 * family: cnn
 * layout: 3
 * default threshold: 5.004
 */
#include "classifier.h"
#include "dsp_config.h"
#include "models.h"

#include "nn_infer.h"
#include "nn_model_data_cnn_small.h"

_Static_assert(NN_MACS_CNN_SMALL <= 1500000u,
               "cnn_small exceeds the multiply-accumulate budget for one window");

/* Two activation buffers, static: at up to NN_MAX_ACT floats each they are far
   too big for the superloop's stack, and the detector runs one window at a time. */
static float s_act_a[NN_MAX_ACT_CNN_SMALL];
static float s_act_b[NN_MAX_ACT_CNN_SMALL];

static float decide(void *ctx, const float *features, uint16_t n)
{
    (void)ctx;
    float out = 0.0f;
    if (n != BOOMDETECT_FEATURE_COUNT_LOGMEL)
    {
        return 0.0f;
    }
    (void)nn_forward(&nn_net_cnn_small, features, s_act_a, s_act_b, &out);
    return out;
}

const classifier_t classifier_cnn_small = {
    .name              = "cnn_small",
    .layout_id         = BOOMDETECT_LAYOUT_LOGMEL,
    .n_features        = BOOMDETECT_FEATURE_COUNT_LOGMEL,
    .feature_offset    = 0u,
    .default_thr_milli = 5004,
    .decide            = decide,
    .ctx               = NULL,
};
