/**
 * @file model_svm_l1.c
 * @brief Linear SVM svm_l1: scaler and a dot product.
 *
 * GENERATED by fw/common/boomdetect/training (bdtrain export); do not edit.
 * Registered by hand in models/models.h and src/classifier_registry.c.
 * run: r2
 * generated: 2026-09-06T20:52:44
 * family: svm
 * layout: 1
 * default threshold: 1.781
 */
#include "classifier.h"
#include "dsp_config.h"
#include "models.h"

#include "arm_math.h"
#include "svm_model_data_svm_l1.h"

#define OFFSET 1u

_Static_assert(OFFSET + SVM_NUM_FEATURES <= BOOMDETECT_FEATURE_COUNT,
               "svm_l1's slice runs past the features its layout produces");

static float decide(void *ctx, const float *features, uint16_t n)
{
    (void)n;
    (void)ctx;
    float32_t scaled[SVM_NUM_FEATURES];
    float32_t dot = 0.0f;
    for (uint32_t i = 0u; i < SVM_NUM_FEATURES; i++)
    {
        scaled[i] = (features[i] - svm_scaler_mean[i]) * svm_scaler_inv_std[i];
    }
    arm_dot_prod_f32(scaled, svm_weights, SVM_NUM_FEATURES, &dot);
    return dot + SVM_BIAS;
}

const classifier_t classifier_svm_l1 = {
    .name              = "svm_l1",
    .layout_id         = BOOMDETECT_LAYOUT_MEAN_STD_DMEAN_CMAX,
    .n_features        = SVM_NUM_FEATURES,
    .feature_offset    = OFFSET,
    .default_thr_milli = 1781,
    .decide            = decide,
    .ctx               = NULL,
};
