/**
 * @file models.h
 * @brief Every classifier_t this package's models/ directory exports.
 *
 * The registry used to carry these as bare `extern` declarations inside its own
 * .c file, which means nothing ever cross-checked them against the definitions:
 * a model file renaming its entry, or giving it a different type, would fail at
 * link time with a symbol name rather than at compile time with the mismatch.
 * Both sides include this instead.
 *
 * Adding a model is still two edits and no more: a file here, and a line in
 * src/classifier_registry.c - plus this declaration, which is what makes the
 * compiler check the pair.
 */
#ifndef BOOMDETECT_MODELS_H
#define BOOMDETECT_MODELS_H

#include "classifier.h"

extern const classifier_t classifier_mlp_v6;
extern const classifier_t classifier_svm_v3;

/* Generated by `bdtrain export` from training run `full` (2026-09-23), trained
   on the whole 61-hour HuggingFace set with the split drawn on recording
   groups. One model per family worth carrying, so the board can score the same
   audio with each. The two linear SVMs of the previous set are gone: retrained
   on this much data they call almost nothing a drone (window TPR 0.00 and 0.08
   on the held-out third).

   Not deployed: the default stays mlp_v6 until field recordings decide. mlp_l2
   is the candidate to replace it - it detects 95 % of held-out drone windows
   against mlp_v6's 42 % at the same false-alarm budget, and alarms on 9 of 9
   Salford flyovers against 1 of 9 - but mlp_v6 still holds the best window AUC
   on Halmstad (0.937 against 0.715), which is the closest thing here to a
   microphone the models have never heard. */
extern const classifier_t classifier_mlp_l2;
extern const classifier_t classifier_gbt_l2;
extern const classifier_t classifier_gbt_reg_l2;
extern const classifier_t classifier_cnn_small;

/* Generated by `bdtrain export` from training run `fw_aug` (2026-09-26): the
   public sets plus the node's own field recordings of a DJI Phantom 4 and a
   Runner 250 and nine kinds of negatives (2026-09-23/25), and four variants of
   each recording heard from 20-250 m (training/boomdetect_train/augment.py: air
   absorption, attenuation, a synthetic floor). mlp_f1 is mlp_reg_l2 of that
   run, gbt_f1 its gbt_reg_l2; both on layout 2, both at the threshold with 5
   false-alarm windows per hour on the public val negatives (squelch 0.003).
   Judged out of fold - every field recording by a model trained without it -
   mlp_f1 alarmed on 6 of 6 DJI and 8 of 11 Runner recordings and on none of 11
   negatives, with 0.26 false alarms per hour on 11.6 h of held-out public
   negatives; made to sound 200 m away, 2 of 6 and 5 of 11 where the model
   trained without the variants managed 0 and 1. Known limit: low-pass the
   input at 6 kHz and neither detects anything. */
extern const classifier_t classifier_mlp_f1;
extern const classifier_t classifier_gbt_f1;

#endif /* BOOMDETECT_MODELS_H */
