/**
 * @file model_mlp_l2.c
 * @brief MLP mlp_l2: scaler, one hidden ReLU layer, logit output.
 *
 * GENERATED by fw/common/boomdetect/training (bdtrain export); do not edit.
 * Registered by hand in models/models.h and src/classifier_registry.c.
 * run: r2
 * generated: 2026-09-06T20:45:43
 * family: mlp
 * layout: 2
 * default threshold: 14.001
 */
#include "classifier.h"
#include "dsp_config.h"
#include "models.h"

#include "arm_math.h"
#include "mlp_model_data_mlp_l2.h"

#define OFFSET 1u

_Static_assert(OFFSET + MLP_NUM_INPUTS == BOOMDETECT_FEATURE_COUNT_STATS_SPECTRAL,
               "mlp_l2's slice does not cover the features its layout produces");

static float decide(void *ctx, const float *features, uint16_t n)
{
    (void)n;
    (void)ctx;
    float32_t x[MLP_NUM_INPUTS];
    float32_t h[MLP_HIDDEN];
    for (uint32_t i = 0u; i < MLP_NUM_INPUTS; i++)
    {
        x[i] = (features[i] - mlp_scaler_mean[i]) * mlp_scaler_inv_std[i];
    }
    for (uint32_t j = 0u; j < MLP_HIDDEN; j++)
    {
        float32_t acc = 0.0f;
        arm_dot_prod_f32(x, mlp_w1[j], MLP_NUM_INPUTS, &acc);
        acc += mlp_b1[j];
        h[j] = (acc > 0.0f) ? acc : 0.0f;
    }
    float32_t out = 0.0f;
    arm_dot_prod_f32(h, mlp_w2, MLP_HIDDEN, &out);
    return out + MLP_B2;
}

const classifier_t classifier_mlp_l2 = {
    .name              = "mlp_l2",
    .layout_id         = BOOMDETECT_LAYOUT_STATS_SPECTRAL,
    .n_features        = MLP_NUM_INPUTS,
    .feature_offset    = OFFSET,
    .default_thr_milli = 14001,
    .decide            = decide,
    .ctx               = NULL,
};
